// Generated by https://quicktype.io

import { ApiReference } from "./commandHandler";

export interface Clazz {
  index: string;
  name: string;
  hit_die: number;
  proficiency_choices: ProficiencyChoice[];
  proficiencies: Proficiency[];
  saving_throws: Proficiency[];
  starting_equipment: StartingEquipment[];
  starting_equipment_options: StartingEquipmentOption[];
  class_levels: string;
  multi_classing: MultiClassing;
  subclasses: Proficiency[];
  url: string;
}

export interface MultiClassing {
  prerequisites: Prerequisite[];
  proficiencies: Proficiency[];
}

export interface Prerequisite {
  ability_score: Proficiency;
  minimum_score: number;
}

export interface Proficiency {
  index: string;
  name: string;
  url: string;
}

export interface ProficiencyChoice {
  choose: number;
  type: string;
  from: Proficiency[];
}

export interface StartingEquipment {
  equipment: Proficiency;
  quantity: number;
}

export interface StartingEquipmentOption {
  choose: number;
  type: string;
  from: FromElement[];
}

export interface FromElement {
  equipment?: Proficiency;
  quantity?: number;
  equipment_option?: EquipmentOption;
}

export interface EquipmentOption {
  choose: number;
  type: string;
  from: EquipmentOptionFrom;
}

export interface EquipmentOptionFrom {
  equipment_category: Proficiency;
}

// Generated by https://quicktype.io

export interface ClassSpecific {
  rage_count: number;
  rage_damage_bonus: number;
  brutal_critical_dice: number;
}

export interface ClassLevel {
  index: string;
  level: number;
  ability_score_bonuses: number;
  prof_bonus: number;
  features: ApiReference[];
  spellcasting: {
    cantrips_known: number;
    spells_known: number;
    spell_slots_level_1: number;
    spell_slots_level_2: number;
    spell_slots_level_3: number;
    spell_slots_level_4: number;
    spell_slots_level_5: number;
    spell_slots_level_6: number;
    spell_slots_level_7: number;
    spell_slots_level_8: number;
    spell_slots_level_9: number;
  };
  class_specific: any;
}
