// Generated by https://quicktype.io

export interface Clazz {
  index: string;
  name: string;
  hit_die: number;
  proficiency_choices: ProficiencyChoice[];
  proficiencies: Proficiency[];
  saving_throws: Proficiency[];
  starting_equipment: StartingEquipment[];
  starting_equipment_options: StartingEquipmentOption[];
  class_levels: string;
  multi_classing: MultiClassing;
  subclasses: Proficiency[];
  url: string;
}

export interface MultiClassing {
  prerequisites: Prerequisite[];
  proficiencies: Proficiency[];
}

export interface Prerequisite {
  ability_score: Proficiency;
  minimum_score: number;
}

export interface Proficiency {
  index: string;
  name: string;
  url: string;
}

export interface ProficiencyChoice {
  choose: number;
  type: string;
  from: Proficiency[];
}

export interface StartingEquipment {
  equipment: Proficiency;
  quantity: number;
}

export interface StartingEquipmentOption {
  choose: number;
  type: string;
  from: FromElement[];
}

export interface FromElement {
  equipment?: Proficiency;
  quantity?: number;
  equipment_option?: EquipmentOption;
}

export interface EquipmentOption {
  choose: number;
  type: string;
  from: EquipmentOptionFrom;
}

export interface EquipmentOptionFrom {
  equipment_category: Proficiency;
}

// Generated by https://quicktype.io

export interface ClassLevel {
  level: number;
  ability_score_bonuses: number;
  prof_bonus: number;
  features: Class[];
  class_specific: ClassSpecific;
  index: string;
  class: Class;
  url: string;
}

export interface Class {
  index: string;
  name: string;
  url: string;
}

export interface ClassSpecific {
  rage_count: number;
  rage_damage_bonus: number;
  brutal_critical_dice: number;
}
